// Constants to get All Products by ADMIN.
export const ADMIN_ALL_PRODUCTS_REQUEST = 'ADMIN_ALL_PRODUCTS_REQUEST';
export const ADMIN_ALL_PRODUCTS_SUCCESS = 'ADMIN_ALL_PRODUCTS_SUCCESS';
export const ADMIN_ALL_PRODUCTS_FAILURE = 'ADMIN_ALL_PRODUCTS_FAILURE';

// New Product Constants.
export const ADMIN_NEW_PRODUCT_REQUEST = 'NEW_PRODUCT_REQUEST';
export const ADMIN_NEW_PRODUCT_SUCCESS = 'NEW_PRODUCT_SUCCESS';
export const ADMIN_NEW_PRODUCT_FAILURE = 'NEW_PRODUCT_FAILURE';
export const ADMIN_NEW_PRODUCT_RESET = 'NEW_PRODUCT_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';