// Constants to get All Products by ADMIN.
export const ADMIN_ALL_PRODUCTS_REQUEST = 'ADMIN_ALL_PRODUCTS_REQUEST';
export const ADMIN_ALL_PRODUCTS_SUCCESS = 'ADMIN_ALL_PRODUCTS_SUCCESS';
export const ADMIN_ALL_PRODUCTS_FAILURE = 'ADMIN_ALL_PRODUCTS_FAILURE';

// Constants to delete a Product by ADMIN.
export const ADMIN_DELETE_PRODUCT_REQUEST = 'ADMIN_DELETE_PRODUCT_REQUEST';
export const ADMIN_DELETE_PRODUCT_SUCCESS = 'ADMIN_DELETE_PRODUCT_SUCCESS';
export const ADMIN_DELETE_PRODUCT_FAILURE = 'ADMIN_DELETE_PRODUCT_FAILURE';
export const ADMIN_DELETE_PRODUCT_RESET = 'ADMIN_DELETE_PRODUCT_RESET';

// Constants to update a product by Admin.
export const ADMIN_UPDATE_PRODUCT_REQUEST = 'ADMIN_UPDATE_PRODUCT_REQUEST';
export const ADMIN_UPDATE_PRODUCT_SUCCESS = 'ADMIN_UPDATE_PRODUCT_SUCCESS';
export const ADMIN_UPDATE_PRODUCT_FAILURE = 'ADMIN_UPDATE_PRODUCT_FAILURE';
export const ADMIN_UPDATE_PRODUCT_RESET = 'ADMIN_UPDATE_PRODUCT_RESET';

// New Product Constants.
export const ADMIN_NEW_PRODUCT_REQUEST = 'NEW_PRODUCT_REQUEST';
export const ADMIN_NEW_PRODUCT_SUCCESS = 'NEW_PRODUCT_SUCCESS';
export const ADMIN_NEW_PRODUCT_FAILURE = 'NEW_PRODUCT_FAILURE';
export const ADMIN_NEW_PRODUCT_RESET = 'NEW_PRODUCT_RESET';

// Constants to get All Reviews of product by ADMIN.
export const ADMIN_ALL_REVIEWS_REQUEST = 'ADMIN_ALL_REVIEWS_REQUEST';
export const ADMIN_ALL_REVIEWS_SUCCESS = 'ADMIN_ALL_REVIEWS_SUCCESS';
export const ADMIN_ALL_REVIEWS_FAILURE = 'ADMIN_ALL_REVIEWS_FAILURE';

// Constants to delete a review of product by ADMIN.
export const ADMIN_DELETE_REVIEW_REQUEST = 'ADMIN_DELETE_REVIEW_REQUEST';
export const ADMIN_DELETE_REVIEW_SUCCESS = 'ADMIN_DELETE_REVIEW_SUCCESS';
export const ADMIN_DELETE_REVIEW_FAILURE = 'ADMIN_DELETE_REVIEW_FAILURE';
export const ADMIN_DELETE_REVIEW_RESET = 'ADMIN_DELETE_REVIEW';

// Constants for admin to get one Product.
export const ADMIN_ONE_PRODUCT_REQUEST = 'ADMIN_ONE_PRODUCT_REQUEST';
export const ADMIN_ONE_PRODUCT_SUCCESS = 'ADMIN_ONE_PRODUCT_SUCCESS';
export const ADMIN_ONE_PRODUCT_FAILURE = 'ADMIN_ONE_PRODUCT_FAILURE';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';