// Constants to get All Orders by ADMIN.
export const ADMIN_ALL_ORDER_REQUEST = 'ADMIN_ALL_ORDER_REQUEST';
export const ADMIN_ALL_ORDER_SUCCESS = 'ADMIN_ALL_ORDER_SUCCESS';
export const ADMIN_ALL_ORDER_FAILURE = 'ADMIN_ALL_ORDER_FAILURE';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';