// Constants to get All Users by ADMIN.
export const ADMIN_ALL_USERS_REQUEST = 'ADMIN_ALL_USERS_REQUEST';
export const ADMIN_ALL_USERS_SUCCESS = 'ADMIN_ALL_USERS_SUCCESS';
export const ADMIN_ALL_USERS_FAILURE = 'ADMIN_ALL_USERS_FAILURE';

// Constants to delete user.
export const ADMIN_DELETE_USER_REQUEST = 'ADMIN_DELETE_USER_REQUEST';
export const ADMIN_DELETE_USER_SUCCESS = 'ADMIN_DELETE_USER_SUCCESS';
export const ADMIN_DELETE_USER_FAILURE = 'ADMIN_DELETE_USER_FAILURE';
export const ADMIN_DELETE_USER_RESET = 'ADMIN_DELETE_USER_RESET';

// Constants to get Update orders.
export const ADMIN_UPDATE_USER_REQUEST = 'ADMIN_UPDATE_USER_REQUEST';
export const ADMIN_UPDATE_USER_SUCCESS = 'ADMIN_UPDATE_USER_SUCCESS';
export const ADMIN_UPDATE_USER_FAILURE = 'ADMIN_UPDATE_USER_FAILURE';
export const ADMIN_UPDATE_USER_RESET = 'ADMIN_UPDATE_USER_RESET';

export const ADMIN_ONE_USER_REQUEST = 'ADMIN_ONE_USER_REQUEST';
export const ADMIN_ONE_USER_SUCCESS = 'ADMIN_ONE_USER_SUCCESS';
export const ADMIN_ONE_USER_FAILURE = 'ADMIN_ONE_USER_FAILURE';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';