// Constants to get All Users by ADMIN.
export const ADMIN_ALL_USERS_REQUEST = 'ADMIN_ALL_USERS_REQUEST';
export const ADMIN_ALL_USERS_SUCCESS = 'ADMIN_ALL_USERS_SUCCESS';
export const ADMIN_ALL_USERS_FAILURE = 'ADMIN_ALL_USERS_FAILURE';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';