// Constants to get All Orders by ADMIN.
export const ADMIN_ALL_ORDER_REQUEST = 'ADMIN_ALL_ORDER_REQUEST';
export const ADMIN_ALL_ORDER_SUCCESS = 'ADMIN_ALL_ORDER_SUCCESS';
export const ADMIN_ALL_ORDER_FAILURE = 'ADMIN_ALL_ORDER_FAILURE';

// Constants to update order by ADMIN.
export const ADMIN_ORDER_UPDATE_REQUEST = 'ADMIN_ORDER_UPDATE_REQUEST';
export const ADMIN_ORDER_UPDATE_SUCCESS = 'ADMIN_ORDER_UPDATE_SUCCESS';
export const ADMIN_ORDER_UPDATE_FAILURE = 'ADMIN_ORDER_UPDATE_FAILURE';
export const ADMIN_ORDER_UPDATE_RESET = 'ADMIN_ORDER_UPDATE_RESET';

// Constants to delete an order by ADMIN.
export const ADMIN_ORDER_DELETE_REQUEST = 'ADMIN_ORDER_DELETE_REQUEST';
export const ADMIN_ORDER_DELETE_SUCCESS = 'ADMIN_ORDER_DELETE_SUCCESS';
export const ADMIN_ORDER_DELETE_FAILURE = 'ADMIN_ORDER_DELETE_FAILURE';
export const ADMIN_ORDER_DELETE_RESET = 'ADMIN_ORDER_DELETE_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';