// Constants to get All Products by ADMIN.
export const ADMIN_ALL_PRODUCTS_REQUEST = 'ADMIN_ALL_PRODUCTS_REQUEST';
export const ADMIN_ALL_PRODUCTS_SUCCESS = 'ADMIN_ALL_PRODUCTS_SUCCESS';
export const ADMIN_ALL_PRODUCTS_FAILURE = 'ADMIN_ALL_PRODUCTS_FAILURE';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';