export const UPDATE_NAME_REQUEST = "UPDATE_NAME_REQUEST";
export const UPDATE_NAME_SUCCESS = "UPDATE_NAME_SUCCESS";
export const UPDATE_NAME_FAIL = "UPDATE_NAME_FAIL";
export const UPDATE_NAME_RESET = "UPDATE_NAME_RESET";

export const UPDATE_EMAIL_REQUEST = "UPDATE_EMAIL_REQUEST";
export const UPDATE_EMAIL_SUCCESS = "UPDATE_EMAIL_SUCCESS";
export const UPDATE_EMAIL_FAIL = "UPDATE_EMAIL_FAIL";
export const UPDATE_EMAIL_RESET = "UPDATE_EMAIL_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";